import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, describe, expect, it } from 'vitest'
import {
  compositeOver,
  contrastRatio,
  parseColor,
  ratioBetween,
  relativeLuminance,
} from './contrast'
import { parseThemeTokens } from './parseTokens'
import { hueDifference } from './perceptual'

const WHITE = { r: 255, g: 255, b: 255 }
const BLACK = { r: 0, g: 0, b: 0 }

const REPORT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../docs/specs/01-spec-broadcast-foundation-shell/artifacts/contrast-report.md',
)

/**
 * Emits the committed contrast report as a side effect of the suite. Generating
 * it here rather than by hand means the report cannot drift from the assertions
 * — if a token changes, the next test run rewrites the numbers.
 */
function writeContrastReport(rows: string[], passes: number, failures: number) {
  const body = [
    '# Contrast report — Broadcast token system',
    '',
    '> Generated by `frontend/src/lib/contrast.test.ts`. Do not edit by hand —',
    '> run `npm run test` from `frontend/` to regenerate.',
    '',
    '## Summary',
    '',
    `- Pairings measured: **${passes + failures}**`,
    `- Passing: **${passes}**`,
    `- Failing: **${failures}**`,
    '',
    'Thresholds: 4.5:1 for foreground text tokens (WCAG 2.1 SC 1.4.3), 3:1 for',
    '`--border-strong`, which bounds interactive controls (SC 1.4.11).',
    '',
    'Translucent surfaces are composited over `--bg-card` before measurement.',
    'Structural border tokens (`--border`, `--border-soft`, `--border-divider`)',
    'draw card edges and table rules rather than identifying controls, and are',
    'deliberately exempt from the non-text floor — holding them to 3:1 would',
    "force heavy outlines that contradict the design's hairline density goal.",
    '',
    '## Pairings',
    '',
    '| Theme | Foreground | Surface | Ratio | Required | Verdict |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n')

  mkdirSync(dirname(REPORT_PATH), { recursive: true })
  writeFileSync(REPORT_PATH, body, 'utf8')
}

// These fixed points come from the WCAG 2.1 definition itself, not from this
// implementation. They are asserted before any palette measurement so that a
// broken ratio function fails here loudly rather than silently "passing" every
// token pairing in the stylesheet.
describe('contrast math known values', () => {
  it('black on white is 21:1', () => {
    expect(contrastRatio(BLACK, WHITE)).toBeCloseTo(21, 5)
  })

  it('a colour against itself is 1:1', () => {
    expect(contrastRatio(WHITE, WHITE)).toBeCloseTo(1, 5)
    expect(contrastRatio(BLACK, BLACK)).toBeCloseTo(1, 5)
  })

  it('is order independent', () => {
    expect(contrastRatio(BLACK, WHITE)).toBeCloseTo(contrastRatio(WHITE, BLACK), 10)
  })

  it('#767676 on white is the canonical AA boundary of ~4.54:1', () => {
    expect(contrastRatio(parseColor('#767676'), WHITE)).toBeCloseTo(4.54, 2)
  })

  it('white has luminance 1 and black 0', () => {
    expect(relativeLuminance(WHITE)).toBeCloseTo(1, 10)
    expect(relativeLuminance(BLACK)).toBeCloseTo(0, 10)
  })
})

describe('parseColor', () => {
  it('parses 6-digit hex', () => {
    expect(parseColor('#f0a92c')).toEqual({ r: 240, g: 169, b: 44, a: 1 })
  })

  it('expands 3-digit hex', () => {
    expect(parseColor('#c00')).toEqual({ r: 204, g: 0, b: 0, a: 1 })
  })

  it('parses rgb() and rgba()', () => {
    expect(parseColor('rgb(10, 20, 30)')).toEqual({ r: 10, g: 20, b: 30, a: 1 })
    expect(parseColor('rgba(255, 255, 255, 0.05)')).toEqual({
      r: 255,
      g: 255,
      b: 255,
      a: 0.05,
    })
  })

  it('throws rather than guessing on unsupported notation', () => {
    expect(() => parseColor('hsl(30 90% 50%)')).toThrow(/Unparseable/)
    expect(() => parseColor('goldenrod')).toThrow(/Unparseable/)
  })
})

describe('compositeOver', () => {
  it('a fully opaque colour is unchanged', () => {
    expect(compositeOver({ ...BLACK, a: 1 }, WHITE)).toEqual(BLACK)
  })

  it('a fully transparent colour becomes the background', () => {
    expect(compositeOver({ ...BLACK, a: 0 }, WHITE)).toEqual(WHITE)
  })

  it('50% black over white is mid grey', () => {
    const result = compositeOver({ ...BLACK, a: 0.5 }, WHITE)
    expect(result.r).toBeCloseTo(127.5, 5)
  })

  // This is the failure mode the compositing step exists to prevent: measured
  // raw, a 5%-alpha white reads as pure white and reports a wildly wrong ratio.
  it('changes the outcome for low-alpha tokens', () => {
    const raw = contrastRatio(parseColor('rgba(255,255,255,0.05)'), BLACK)
    const composited = contrastRatio(
      compositeOver(parseColor('rgba(255,255,255,0.05)'), BLACK),
      BLACK,
    )
    expect(raw).toBeGreaterThan(20)
    expect(composited).toBeLessThan(1.2)
  })
})

describe('ratioBetween', () => {
  it('resolves translucent foregrounds against their surface', () => {
    expect(ratioBetween('#000000', '#ffffff', '#ffffff')).toBeCloseTo(21, 2)
  })
})

/**
 * FR U1-7: "All text/background pairings shall meet WCAG 2.1 AA contrast
 * (4.5:1 for body text, 3:1 for large text and UI boundaries) in both themes."
 *
 * Every foreground token is measured against every surface it can actually
 * appear on. Translucent surfaces are composited over --bg-card first, because
 * that is the panel they sit inside; measuring their raw rgba() values would
 * ignore the alpha and report ratios unrelated to what a user sees.
 *
 * Running this suite regenerates the committed contrast report, so the report
 * can never drift from the values actually asserted here.
 */
const FOREGROUND_TOKENS = [
  '--text-strong',
  '--text-primary',
  '--text-secondary',
  '--text-muted',
  '--text-faint',
  '--accent',
  '--accent-hover',
  '--success',
  '--danger',
  '--warn',
]

const SURFACE_TOKENS = [
  '--bg-page',
  '--bg-card',
  '--bg-selected',
  '--bg-subtle',
  '--bg-hover',
  '--bg-row-stripe',
]

/**
 * Only --border-strong is held to the 3:1 non-text floor.
 *
 * WCAG 1.4.11 covers boundaries needed to *identify* a control. --border-strong
 * bounds the league select, text inputs, and the secondary/danger/logout
 * buttons, so it qualifies. --border, --border-soft and --border-divider draw
 * card edges and table rules — structural, not identifying — and holding them
 * to 3:1 would force heavy outlines that contradict the spec's hairline density
 * goal. They are exempt by design, not by oversight.
 */
const CONTROL_BORDER_TOKENS = ['--border-strong']
const CONTROL_BORDER_SURFACES = ['--bg-page', '--bg-card']

const AA_BODY_TEXT = 4.5
const AA_NON_TEXT = 3

function resolveSurface(tokens: Record<string, string>, name: string) {
  const page = parseColor(tokens['--bg-page'])
  const card = parseColor(tokens['--bg-card'])
  const raw = parseColor(tokens[name])
  if (raw.a === 1) return compositeOver(raw, { r: 255, g: 255, b: 255 })
  // Translucent surfaces are painted inside a card, so that is their backdrop.
  return compositeOver(raw, compositeOver(card, compositeOver(page, { r: 255, g: 255, b: 255 })))
}

describe('WCAG AA contrast across both themes (FR U1-7)', () => {
  const themes = parseThemeTokens()
  const reportRows: string[] = []
  let failures = 0
  let passes = 0

  for (const [themeName, tokens] of Object.entries(themes)) {
    describe(themeName, () => {
      for (const surfaceName of SURFACE_TOKENS) {
        const surface = resolveSurface(tokens, surfaceName)

        for (const fgName of FOREGROUND_TOKENS) {
          const fg = compositeOver(parseColor(tokens[fgName]), surface)
          const ratio = Math.round(contrastRatio(fg, surface) * 100) / 100
          const ok = ratio >= AA_BODY_TEXT
          ok ? passes++ : failures++
          reportRows.push(
            `| ${themeName} | \`${fgName}\` | \`${surfaceName}\` | ${ratio.toFixed(2)}:1 | ${AA_BODY_TEXT}:1 | ${ok ? 'PASS' : '**FAIL**'} |`,
          )

          it(`${fgName} on ${surfaceName} meets ${AA_BODY_TEXT}:1`, () => {
            expect(ratio).toBeGreaterThanOrEqual(AA_BODY_TEXT)
          })
        }
      }

      for (const borderName of CONTROL_BORDER_TOKENS) {
        for (const surfaceName of CONTROL_BORDER_SURFACES) {
          const surface = resolveSurface(tokens, surfaceName)
          const border = compositeOver(parseColor(tokens[borderName]), surface)
          const ratio = Math.round(contrastRatio(border, surface) * 100) / 100
          const ok = ratio >= AA_NON_TEXT
          ok ? passes++ : failures++
          reportRows.push(
            `| ${themeName} | \`${borderName}\` | \`${surfaceName}\` | ${ratio.toFixed(2)}:1 | ${AA_NON_TEXT}:1 | ${ok ? 'PASS' : '**FAIL**'} |`,
          )

          it(`${borderName} on ${surfaceName} meets ${AA_NON_TEXT}:1`, () => {
            expect(ratio).toBeGreaterThanOrEqual(AA_NON_TEXT)
          })
        }
      }
    })
  }

  afterAll(() => {
    writeContrastReport(reportRows, passes, failures)
  })
})

/**
 * FR U1-5: "express semantic status (positive/negative deltas) through tokens
 * distinct from the accent token."
 *
 * The parenthetical scopes this to the delta pair — --success and --danger,
 * which style the .pos/.neg classes on the avg_plus_minus column. --warn is
 * excluded: it carries no delta semantics in this app (it styles the Manage
 * Leagues edit button and the championship round badge).
 *
 * Measured as hue separation, NOT contrast ratio. Contrast ratio is a
 * luminance metric: an amber accent and a green success token score ~1.1:1
 * because they sit at similar lightness, despite being impossible to confuse.
 * Requiring luminance separation here would force the delta colours far
 * lighter or darker than the accent and destroy their ability to read as peers
 * in the same table column.
 *
 * The 25-degree threshold marks the edge of "same hue family". It is not
 * load-bearing — the measured values clear it by a wide margin.
 */
describe('delta tokens are distinct from the accent (FR U1-5)', () => {
  const themes = parseThemeTokens()
  const MIN_HUE_SEPARATION = 25

  for (const [themeName, tokens] of Object.entries(themes)) {
    describe(themeName, () => {
      it('--success is distinct from --accent', () => {
        expect(hueDifference(tokens['--accent'], tokens['--success'])).toBeGreaterThanOrEqual(
          MIN_HUE_SEPARATION,
        )
      })

      it('--danger is distinct from --accent', () => {
        expect(hueDifference(tokens['--accent'], tokens['--danger'])).toBeGreaterThanOrEqual(
          MIN_HUE_SEPARATION,
        )
      })

      // The two delta colours carry opposite meanings in the same column, so
      // confusing them is worse than confusing either with the accent.
      it('--success and --danger are distinct from each other', () => {
        expect(hueDifference(tokens['--success'], tokens['--danger'])).toBeGreaterThanOrEqual(
          MIN_HUE_SEPARATION,
        )
      })
    })
  }
})
